name: Run tests and upload coverage

on: 
  push

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npx vitest run --coverage

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Report results to DeepSource
        run: |
          # Tests have finished and a test coverage report is available
      
          # Install deepsource CLI
            curl https://deepsource.io/cli | sh
      
          # From the root directory, run the report coverage command
            ./bin/deepsource report --analyzer test-coverage --key javascript --value-file ./codecov
      
        env:
            DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
